-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 21:13:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cinema` ;

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf8 ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`hall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`hall` ;

CREATE TABLE IF NOT EXISTS `cinema`.`hall` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `column` INT(10) UNSIGNED NOT NULL,
  `row` INT(10) UNSIGNED NOT NULL,
  `size` TINYINT(4) NOT NULL,
  `is_Imax` TINYINT(4) NOT NULL,
  `is3D` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`movie` ;

CREATE TABLE IF NOT EXISTS `cinema`.`movie` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `poster` VARCHAR(255) NULL DEFAULT NULL,
  `director` VARCHAR(45) NOT NULL,
  `screen_writer` VARCHAR(45) NOT NULL,
  `starring` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  `duration` INT(10) UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `description` TEXT NOT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`arrangement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`arrangement` ;

CREATE TABLE IF NOT EXISTS `cinema`.`arrangement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `start_time` DATE NOT NULL,
  `end_time` DATE NOT NULL,
  `fare` FLOAT UNSIGNED NOT NULL,
  `hall_id` INT(11) NOT NULL,
  `movie_id` INT(11) NOT NULL,
  `visible_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_arrangement_hall1_idx` (`hall_id` ASC),
  INDEX `fk_arrangement_movie1_idx` (`movie_id` ASC),
  CONSTRAINT `fk_arrangement_hall1`
    FOREIGN KEY (`hall_id`)
    REFERENCES `cinema`.`hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arrangement_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `cinema`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`seat` ;

CREATE TABLE IF NOT EXISTS `cinema`.`seat` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `column` INT(11) NOT NULL,
  `row` INT(11) NOT NULL,
  `hall_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seat_hall1_idx` (`hall_id` ASC),
  CONSTRAINT `fk_seat_hall1`
    FOREIGN KEY (`hall_id`)
    REFERENCES `cinema`.`hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`arrangement_seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`arrangement_seat` ;

CREATE TABLE IF NOT EXISTS `cinema`.`arrangement_seat` (
  `is_locked` TINYINT(4) NOT NULL DEFAULT '0',
  `arrangement_id` INT(11) NOT NULL,
  `seat_id` INT(11) NOT NULL,
  INDEX `fk_arrangement_seat_arrangement1_idx` (`arrangement_id` ASC),
  INDEX `fk_arrangement_seat_seat1_idx` (`seat_id` ASC),
  CONSTRAINT `fk_arrangement_seat_arrangement1`
    FOREIGN KEY (`arrangement_id`)
    REFERENCES `cinema`.`arrangement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arrangement_seat_hall1`
    FOREIGN KEY (`seat_id`)
    REFERENCES `cinema`.`seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`promotion` ;

CREATE TABLE IF NOT EXISTS `cinema`.`promotion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `start_time` DATE NOT NULL,
  `end_time` DATE NOT NULL,
  `specify_movies` TINYINT(4) NOT NULL DEFAULT '0',
  `target_amount` FLOAT UNSIGNED NOT NULL,
  `coupon_amount` FLOAT UNSIGNED NOT NULL,
  `coupon_expiration` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`user` ;

CREATE TABLE IF NOT EXISTS `cinema`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`coupon` ;

CREATE TABLE IF NOT EXISTS `cinema`.`coupon` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `end_time` DATE NOT NULL,
  `promotion_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coupon_promotion1_idx` (`promotion_id` ASC),
  INDEX `fk_coupon_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_coupon_promotion1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `cinema`.`promotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coupon_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`manager` ;

CREATE TABLE IF NOT EXISTS `cinema`.`manager` (
  `user_id` INT(11) NOT NULL,
  `root` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`),
  INDEX `fk_manager_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_manager_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`movie_like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`movie_like` ;

CREATE TABLE IF NOT EXISTS `cinema`.`movie_like` (
  `user_id` INT(11) NOT NULL,
  `movie_id` INT(11) NOT NULL,
  INDEX `fk_user_has_movie_movie1_idx` (`movie_id` ASC),
  INDEX `fk_user_has_movie_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_movie_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `cinema`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_movie_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`recharge_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`recharge_record` ;

CREATE TABLE IF NOT EXISTS `cinema`.`recharge_record` (
  `id` INT(11) NOT NULL,
  `original_amount` FLOAT UNSIGNED NOT NULL,
  `discount_amount` FLOAT NOT NULL,
  `date` DATE NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recharge_record_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_recharge_record_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`refund_strategy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`refund_strategy` ;

CREATE TABLE IF NOT EXISTS `cinema`.`refund_strategy` (
  `day` INT(11) NOT NULL,
  `refundable` TINYINT(4) NOT NULL DEFAULT '1',
  `percentage` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`day`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`staff` ;

CREATE TABLE IF NOT EXISTS `cinema`.`staff` (
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_staff_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_staff_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`tickets` ;

CREATE TABLE IF NOT EXISTS `cinema`.`tickets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `arrangement_id` INT(11) NOT NULL,
  `seat_id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `status` TINYINT(4) NOT NULL,
  `real_amount` FLOAT UNSIGNED NOT NULL,
  `orderID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_user1_idx` (`user_id` ASC),
  INDEX `fk_tickets_arrangement1_idx` (`arrangement_id` ASC),
  INDEX `fk_tickets_seat1_idx` (`seat_id` ASC),
  CONSTRAINT `fk_tickets_arrangement1`
    FOREIGN KEY (`arrangement_id`)
    REFERENCES `cinema`.`arrangement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_seat1`
    FOREIGN KEY (`seat_id`)
    REFERENCES `cinema`.`seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`vipcard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`vipcard` ;

CREATE TABLE IF NOT EXISTS `cinema`.`vipcard` (
  `balance` FLOAT UNSIGNED NOT NULL DEFAULT '0',
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_vipcard_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`vipcard_recharge_reduction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`vipcard_recharge_reduction` ;

CREATE TABLE IF NOT EXISTS `cinema`.`vipcard_recharge_reduction` (
  `target_amount` INT(10) UNSIGNED NOT NULL,
  `discount_amount` FLOAT NOT NULL,
  PRIMARY KEY (`target_amount`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`promotion_has_movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`promotion_has_movie` ;

CREATE TABLE IF NOT EXISTS `cinema`.`promotion_has_movie` (
  `promotion_id` INT(11) NOT NULL,
  `movie_id` INT(11) NOT NULL,
  PRIMARY KEY (`promotion_id`, `movie_id`),
  INDEX `fk_promotion_has_movie_movie1_idx` (`movie_id` ASC),
  INDEX `fk_promotion_has_movie_promotion1_idx` (`promotion_id` ASC),
  CONSTRAINT `fk_promotion_has_movie_promotion1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `cinema`.`promotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promotion_has_movie_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `cinema`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
